### PR TITLE
grsim implemented dribble primitive

### LINKED ISSUE #107: grSim backend - Implement Dribble Primitive
[grSim](https://github.com/RoboCup-SSL/grSim) is the "standard" simulator for the SSL Division, and is the simulator we use.

Because we currently don't/can't simulate our robot's firmware, we need to re-create how we move and control the robots for the simulator. Rather than sending a Primitive command to a robot over radio, which will then be executed by the robot firmware in order to do whatever the command asks, we need to send different commands to the simulator to move the robots.

We already have the ability to send commands to the simulator with #12 . The ability to control a robot's movement is further abstracted by the motion controller developed in #9 . This imitates the bang-bang motion controller on our robots, so that robot's will speed up and slow down more realistically as the move in the simulator.

The task here is to create a function/routine to implement our Dribble Primitive using this motion-controller abstraction, so this Primitive can be simulated. We need these primitive to work in the simulator so we can actually use the simulator for testing.

The spec for the Dribble Primitive can be found in #86 , and also in the DribblePrimitive class from #104  

The DribblePrimitive class will be the input. The exact place this code will go will be revised once #9 is merged, and we will update the ticket.

**Note**: I have no idea how dribbling will work in grSim. This may or may not work as expected.

### PR DESCRIPTION
**Pull request by roark-z**
### Description

implemented and tested the dribble primitive for grsim

### Testing Done

Began unit tests for the implementation

### Resolved Issues

resolves #107 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

File: src/thunderbots/software/test/ai/grsim_communication/dribble_primitive.cpp [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+#include <gtest/gtest.h>
+#include <string.h>
+
+#include "ai/world/robot.h"
+#include "grsim_communication/grsim_command_primitive_visitor.h"
+
+TEST(GrsimCommandPrimitiveVisitorTest, visit_dribble_primitive_kick_allowed)
+{
+    DribblePrimitive* dribble_primitive =
```
Comment (MathewMacDougall) [inline src/thunderbots/software/test/ai/grsim_communication/dribble_primitive.cpp]: There's no reason for this variable to be a pointer, and we _definitely_ shouldn't use raw pointers. In general it's good practice to only use pointers when necessary, and use smart-pointers instead of raw pointers. This goes for the entire file.

File: src/thunderbots/software/test/ai/grsim_communication/dribble_primitive.cpp [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+
+    auto motion_controller_command =
+            grsimCommandPrimitiveVisitor->getMotionControllerCommand();
+
+    EXPECT_EQ(motion_controller_command.global_destination, Point(-0.2, 1));
+    EXPECT_EQ(motion_controller_command.final_orientation, Angle::ofDegrees(75));
+    EXPECT_EQ(motion_controller_command.kick_speed_meters_per_second, 0.0);
+    EXPECT_TRUE(motion_controller_command.dribbler_on);
+EXPECT_FALSE(motion_controller_command.chip_instead_of_kick);
+}
```
Comment (MathewMacDougall) [inline src/thunderbots/software/test/ai/grsim_communication/dribble_primitive.cpp]: nit: no newline at the end of the file

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
I know this is WIP but throwing in some early comments.

File: src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp [hunk 3]
```diff
@@ -154,6 +154,13 @@ void GrsimCommandPrimitiveVisitor::visit(const PivotPrimitive &pivot_primitive)
 void GrsimCommandPrimitiveVisitor::visit(const DribblePrimitive &dribble_primitive)
 {
     // TODO: https://github.com/UBC-Thunderbots/Software/issues/107
```
Comment (garethellis0) [inline src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp]: we should remove this `TODO`

File: src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp [hunk 4]
```diff
@@ -154,6 +154,13 @@ void GrsimCommandPrimitiveVisitor::visit(const PivotPrimitive &pivot_primitive)
...
+
+    float kickPower = dribble_primitive.isSmallKickAllowed() ? 5.0f : 0.0f;
```
Comment (garethellis0) [inline src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp]: Where is `5.0f` coming from here? We should probably make this a named constant, and it should probably go in the `constants.h` file (though that would depend on if we'll use this constant elsewhere).

**Review by garethellis0 — CHANGES_REQUESTED** [review]

File: src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp [hunk 5]
```diff
@@ -153,14 +153,12 @@ void GrsimCommandPrimitiveVisitor::visit(const PivotPrimitive &pivot_primitive)
 
 void GrsimCommandPrimitiveVisitor::visit(const DribblePrimitive &dribble_primitive)
 {
-    // TODO: https://github.com/UBC-Thunderbots/Software/issues/107
-
-    float kickPower = dribble_primitive.isSmallKickAllowed() ? 0.5f : 0.0f;
+    float kickPower =
```
Comment (MathewMacDougall) [inline src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp]: nit: if you just make this a `double` you won't need to cast. And if you are going to cast, use `static_cast`. It's slightly safer / better convention.

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
Changes overall look good. There's some build failures which I think are because #411 was merged recently, which slightly changed the interface of the `MotionController` since it's now a class. You might want to update your branch again in case you didn't get that change, and update your usage of the `MotionController` accordingly.

File: src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp [hunk 6]
```diff
@@ -153,7 +153,12 @@ void GrsimCommandPrimitiveVisitor::visit(const PivotPrimitive &pivot_primitive)
 
 void GrsimCommandPrimitiveVisitor::visit(const DribblePrimitive &dribble_primitive)
 {
-    // TODO: https://github.com/UBC-Thunderbots/Software/issues/107
+    float kickPower =
+        (float)(dribble_primitive.isSmallKickAllowed() ? DRIBBLE_SMALL_KICK_POWER : 0.0);
+
+    motion_controller_command = MotionController::MotionControllerCommand(
+        dribble_primitive.getDestination(), dribble_primitive.getFinalAngle(),
+        dribble_primitive.getFinalSpeed(), kickPower, false, true);
```
Comment (MathewMacDougall) [inline src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp]: The way `kickPower` is being used here, the robot will always kick the ball when it comes into contact with it, which isn't quite right since then we won't spend time dribbling. We only need to do a small kick before we have moved 1 meter from the starting location of our dribble, so we don't violate the rules.

(The rules are that the robot cannot dribble the ball for more than 1 meter without releasing the ball)

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]

**Comment by garethellis0** [comment]
@SupoWupo - please let me know when you'd like a re-review from me!

File: src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp (hunk 6 above)
Comment (MathewMacDougall) [reply src/thunderbots/software/grsim_communication/grsim_command_primitive_visitor.cpp]: After some offline discussion we are leaving this for now as it's not a priority, and wouldn't be simulated well anyway.

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Comment by MathewMacDougall** [comment]
@SupoWupo 	merge this please
