### PR TITLE
Make The PassGenerator (Optionally) Deterministic

### LINKED ISSUE #655: Fix Flaky PassGenerator Tests
### Description of the task
Re-enable and fix all the tests in `test/.../pass_generator.cpp`. Currently they are all flaky and often fail.

### Blocked By
#766

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Modifications to the `PassGenerator` to enable it to be run deterministically for the purposes of testing.

### Testing Done
Unit tests pass.

### Resolved Issues
Resolves #655 .

### Length Justification
N.A.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

File: src/software/ai/passing/pass_generator.h [hunk 1]
```diff
@@ -128,6 +133,9 @@ namespace Passing
         // (pass_start_x, pass_start_y, pass_speed, pass_start_time)
         static const int NUM_PARAMS_TO_OPTIMIZE = 4;
 
+        // The number of iterations to run on each call to `getBestPassSoFar()`
+        // **if** running determinstically
+        static const size_t NUM_ITERS_PER_DETERMINISTIC_CALL = 10;
```
Comment (MathewMacDougall) [inline src/software/ai/passing/pass_generator.h:140]: Where did this number come from? The average number of iterations run while using threads?

File: src/software/ai/passing/pass_generator_test.cpp [hunk 2]
```diff
@@ -61,14 +56,11 @@ class PassGeneratorTest : public testing::Test
             // time has expired, whichever comes first. We also check that the score
```
Comment (MathewMacDougall) [inline src/software/ai/passing/pass_generator_test.cpp:56]:
```suggestion
            // number of iterations have been run, whichever comes first. We also check that the score
```

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
Looks reasonable, just very minor comments.

**Comment by EvanMorcom** [comment]
For my own clarity here, the deterministic part you're adding is that the pass generator is run X number of times vs the optimization thread being run for Y seconds (and any number of iterations within that)?

File: src/software/ai/passing/pass_generator.h (hunk 1 above)
Comment (garethellis0) [reply src/software/ai/passing/pass_generator.h:140]: Fairly random to be honest, just made sure it worked well for tests. Eventually this will probably need to be exposed, but in the interests of keeping this small, YAGNI.

**Comment by garethellis0** [comment]
> For my own clarity here, the deterministic part you're adding is that the pass generator is run X number of times vs the optimization thread being run for Y seconds (and any number of iterations within that)?

Yep!

**Review by MathewMacDougall — DISMISSED** [review]
LGTM pending CI

**Comment by garethellis0** [comment]
@MathewMacDougall - gonna need re-review on this

File: src/software/ai/passing/pass_generator.h (hunk 1 above)
Comment (MathewMacDougall) [reply src/software/ai/passing/pass_generator.h:140]: Can you leave a quick comment saying that? Just to give people enough context that this _isn't_ a carefully chosen value based on a bunch of tests with threading.

File: src/software/ai/passing/pass_generator_test.cpp [hunk 3]
```diff
@@ -61,14 +56,11 @@ class PassGeneratorTest : public testing::Test
...
-                 seconds_so_far < max_num_seconds);
-
-        ASSERT_LT(seconds_so_far, max_num_seconds)
-            << "Pass generator did not converge after running for " << max_num_seconds
-            << " seconds";
+            if (std::abs(curr_score - prev_score) < min_score_diff)
+            {
+                break;
+            }
+        }
```
Comment (MathewMacDougall) [inline src/software/ai/passing/pass_generator_test.cpp:63]: Do we not need an `ASSERT` in this function anymore?

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]

**Review by EvanMorcom — DISMISSED** [review]
LGTM pending Matt's comments.

Is there any reason why we don't run a deterministic # of iterations in another thread?

**Comment by garethellis0** [comment]
> LGTM pending Matt's comments.
> 
> Is there any reason why we don't run a deterministic # of iterations in another thread?

Sorry, not sure I follow, how would you make that deterministic?

File: src/software/ai/passing/pass_generator.h (hunk 1 above)
Comment (garethellis0) [reply src/software/ai/passing/pass_generator.h:140]: Yep, no problem. Added a comment.

File: src/software/ai/passing/pass_generator_test.cpp (hunk 3 above)
Comment (garethellis0) [reply src/software/ai/passing/pass_generator_test.cpp:63]: We don't, that was for some checks I had that were needed when things weren't deterministic. Looking at this made me realize that there is a check we could use here though, added:
```
        EXPECT_LE(std::abs(curr_score - prev_score), min_score_diff);
```
after the loop.

**Review by MathewMacDougall — DISMISSED** [review]

**Comment by EvanMorcom** [comment]
Since the optimizer is run in a different thread, it seems more consistent to me to have a function optimizePass(int num_iterations) that has it's own thread but returns after num_iterations.

Would that not still be deterministic as (assuming this is for unit tests) the data doesn't change?

But I'm totally good with what you have as-is, just a comment.

**Comment by garethellis0** [comment]
Oh, yes for the unit tests that would probably work (though there is some complexity with the destructor). The long term goal for this is to make the AI deterministic so that our simulator unit tests aren't flaky. In that case there are no guarantees about when update methods on the `PassGenerator` will be called.

File: src/software/ai/passing/pass_generator.cpp [hunk 4]
```diff
@@ -9,26 +9,30 @@
...
+                             const PassType& pass_type, bool running_deterministically)
     : updated_world(world),
       world(world),
       passer_robot_id(std::nullopt),
       optimizer(optimizer_param_weights),
       passer_point(passer_point),
       best_known_pass({0, 0}, {0, 0}, 0, Timestamp::fromSeconds(0)),
       target_region(std::nullopt),
-      random_num_gen(random_device()),
+      random_num_gen(13),
```
Comment (jonathanlew) [inline src/software/ai/passing/pass_generator.cpp:23]: Is this is a magic number? Maybe pull it out as a constant and add a comment

**Review by jonathanlew — CHANGES_REQUESTED** [review]
Looks reasonable. I agree with what Mat and Evan said about number of iterations.

File: src/software/ai/passing/pass_generator.cpp (hunk 4 above)
Comment (garethellis0) [reply src/software/ai/passing/pass_generator.cpp:23]: Added a comment:
```
      // We initialize the random number generator with a specific value to 
      // allow generated passes to be deterministic. The value used here has
      // no special meaning.

```

**Review by jonathanlew — APPROVED** [review]
LGTM! :+1:

**Review by MathewMacDougall — APPROVED** [review]
