### PR TITLE
Better Ball Update

### LINKED ISSUE #3197: Broken or misaligned breakbeams should not produce incorrect ball position in SensorFusion
A problem that we had in Robocup last year was that our breakbeams would fault in a tripped state (i.e. they would say that we have a ball when we actually don't). Our sensor fusion code assumed that since we had the ball in our dribbler, the ball must be near our robot even if the camera data says we are somewhere else. This led to situations where we would think we had the ball on one side of the field while the enemy team had an open shot on net.

We want to solve this problem by making sensor_fusion (which is in charge of creating the World object that the rest of our AI depends on) more robust.

If we get a breakbeam tripped message from the robot and the camera data says that the ball is more than a X threshold away from the actual robot, we're going to rely on camera data instead. Relevant code: https://github.com/UBC-Thunderbots/Software/blob/1528173facd4b72d7fd4265e99da5ca9e26b1e3d/src/software/sensor_fusion/sensor_fusion.cpp#L253

Checklist:
- [ ] Write a unit test for a stray ball detection and tripped robot using mocked `RobotStatus` protos in `sensor_fusion_test.cpp`
- [ ] Modify `sensor_fusion.cpp` to create a `World` using camera data if any robot's breakbeam is tripped but the robot is far away from where the camera thinks the ball is

### PR DESCRIPTION
**Pull request by Mr-Anyone**
### Description

Implemented a feature so that the ball update is a bit better than before. The idea is the to calculate the distance between the robot that has a breakbeam trigger and the ball. If that distance is too big, we know for sure that the breakbeam is at fault and we ignore updating the ball using the position of the robot!

### Testing Done

Write some stuff in the `src/software/sensor_fusion/sensor_fusion_test.cpp` . Probably needs field testing. I am ran thunderscope and thunderscope seems to be stable. 

### Resolved Issues

resolves #3197

### Length Justification and Key Files to Review

N/A

### Review Checklist

- [X] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 1]
```diff
@@ -180,6 +180,59 @@ void SensorFusion::updateWorld(
...
+    Point robot_position = robot.position();
+    Point ball_position  = ball.position();
+
+    double x_difference = ball_position.x() - robot_position.x();
+    double y_difference = ball_position.y() - robot_position.y();
+
+    // using the classic distance formula
+    return static_cast<float>(
+        std::sqrt(x_difference * x_difference + y_difference * y_difference));
+}
```
Comment (nimazareian) [inline src/software/sensor_fusion/sensor_fusion.cpp]: nit: You can use `Vector::length` to calculate the length of a vector, alternatively, you could use our `distance` function to calculate the distance between two points directly.

Also, for cleanliness and not needing to cast values, we should stick to using doubles wherever possible.

File: src/software/sensor_fusion/sensor_fusion.h [hunk 2]
```diff
@@ -48,13 +48,32 @@ class SensorFusion
...
 
+    /**
+     * This function controls the behavior of how the ball is being updated. If this
+     * returns True, we use the position of the robot that triggers the breakbeam instead
+     * of the one given by the ssl vision system.
+     *
+     * @return True if we were to use the position of the robot instead of the ssl camera
+     * system. False otherwise
+     */
+    bool shouldUseRobotBallPositionInsteadOfSSL(
```
Comment (nimazareian) [inline src/software/sensor_fusion/sensor_fusion.h]: nit:
```suggestion
    bool shouldUseBreakbeamBallPositionInsteadOfVision(
```

File: src/software/sensor_fusion/sensor_fusion.h [hunk 3]
```diff
@@ -48,13 +48,32 @@ class SensorFusion
...
     static constexpr unsigned int VISION_PACKET_RESET_COUNT_THRESHOLD = 5;
     // Vision packets before this threshold time indicate that the vision client has just
     // started, determined experimentally with the simulator
     static constexpr double VISION_PACKET_RESET_TIME_THRESHOLD = 0.5;
 
+    // This is used for detecting if the breakbeam is at fault. The idea is that distance
+    // between the robot that has the ball is greater than the distance below, then we
+    // know that the breakbeam has a problem see for more:
+    // https://github.com/UBC-Thunderbots/Software/issues/3197
+    static constexpr float DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION = 0.5f;
```
Comment (nimazareian) [inline src/software/sensor_fusion/sensor_fusion.h]: nit:
```suggestion
    static constexpr double DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION_METERS = 0.5;
```

**Review by nimazareian — COMMENTED** [review]
I had some initial comments. Will review the rest later.

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 4]
```diff
@@ -180,6 +180,55 @@ void SensorFusion::updateWorld(
...
+{
+    Vector robot_position = {robot.position().x(), robot.position().y()};
+    Vector ball_position  = {ball.position().x(), ball.position().y()};
+
+    // using the classic distance formula
+    return (ball_position - robot_position).length();
+}
+
+
+bool SensorFusion::shouldUseRobotBallPositionInsteadOfVision(
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp]: I think `shouldTrustRobotStatus` is a better name

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 5]
```diff
@@ -180,6 +180,55 @@ void SensorFusion::updateWorld(
...
+    }
+
+    std::optional<Ball> ball = createBall(ball_detection);
+    if (!ball.has_value())
+    {
+        return false;
+    }
+
+    double distance = computeDistanceBetweenBallAndRobot(
+        robot_with_ball_in_dribbler.value(), ball.value());
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp]:
```suggestion
    double distance = (robot_with_ball_in_dribbler.value().position() - ball.value().position()).length()
```

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 6]
```diff
@@ -180,6 +180,55 @@ void SensorFusion::updateWorld(
...
 }
 
+static double computeDistanceBetweenBallAndRobot(const Robot &robot, const Ball &ball)
+{
+    Vector robot_position = {robot.position().x(), robot.position().y()};
+    Vector ball_position  = {ball.position().x(), ball.position().y()};
+
+    // using the classic distance formula
+    return (ball_position - robot_position).length();
+}
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp]: I'm not sure we need this function -- we've overridden a couple of operators to do this inline easily

see below

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 7]
```diff
@@ -875,3 +875,114 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
...
+    Vector velocity(0, 0);
+    ball_state = BallState{position, velocity};
+
+    yellow_robot_states.clear();
+    blue_robot_states.clear();
+
+    RobotState robot_state(Point(0, 0), Vector(0, 0), Angle::fromRadians(2),
+                           AngularVelocity::zero());
+    RobotStateWithId robot_id = {2, robot_state};
+    // blue_robot_states.push_back(robot_id);
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]: delete commented out code

File: src/software/sensor_fusion/sensor_fusion.h [hunk 8]
```diff
@@ -48,13 +48,32 @@ class SensorFusion
...
+     * This function controls the behavior of how the ball is being updated. If this
+     * returns True, we use the position of the robot that triggers the breakbeam instead
+     * of the one given by the ssl vision system.
+     *
+     * @return True if we were to use the position of the robot instead of the ssl camera
+     * system. False otherwise
+     */
+    bool shouldUseRobotBallPositionInsteadOfVision(
+        const SSLProto::SSL_DetectionFrame &frame,
+        const std::vector<BallDetection> &ball_detection);
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.h]: I think this is more appropriate as a private function

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 9]
```diff
@@ -875,3 +875,114 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
...
+    sensor_fusion.processSensorProto(sensor_msg);
+
+    // actually tesing the ball detection
+    std::vector<BallDetection> ball_detection =
+        createBallDetections({*(ssl_wrapper_packet->mutable_detection())});
+
+    bool state = sensor_fusion.shouldUseRobotBallPositionInsteadOfVision(
+        *(ssl_wrapper_packet->mutable_detection()), ball_detection);
+
+    EXPECT_TRUE(state);
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]: you should call `sensor_fusion.getWorld()` instead and assert on ball position

Comment (itsarune) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: same thing below

File: src/software/sensor_fusion/sensor_fusion.h (hunk 8 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.h]: Yes, I do also think so. 

The problem with is that I can't test this function. I am not quite sure how you friend this class for gtest.

Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.h]: Nvm, I  just saw the comment below.

**Review by itsarune — COMMENTED** [review]
left a few comments.

It looks like a couple of the simulated gameplay tests failed, and it looks like it's related to your changes.

File: src/software/sensor_fusion/sensor_fusion.cpp (hunk 4 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp]: agreed

File: src/software/sensor_fusion/sensor_fusion.cpp (hunk 5 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp]: resolved

File: src/software/sensor_fusion/sensor_fusion.cpp (hunk 6 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp]: resolved: I did not know that existed.

File: src/software/sensor_fusion/sensor_fusion_test.cpp (hunk 7 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: done.

File: src/software/sensor_fusion/sensor_fusion_test.cpp (hunk 9 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: done.

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 10]
```diff
@@ -231,31 +271,28 @@ void SensorFusion::updateWorld(const SSLProto::SSL_DetectionFrame &ssl_detection
...
         std::optional<Robot> robot_with_ball_in_dribbler =
             friendly_team.getRobotById(friendly_robot_id_with_ball_in_dribbler.value());
 
-        if (robot_with_ball_in_dribbler.has_value())
+        std::vector<BallDetection> dribbler_in_ball_detection = {BallDetection{
+            .position =
+                robot_with_ball_in_dribbler->position() +
+                Vector::createFromAngle(robot_with_ball_in_dribbler->orientation())
+                    // MAX_FRACTION_OF_BALL_COVERED_BY_ROBOT of the ball should be
+                    // inside the robot
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp]: what is this comment referring to? is this supposed to be here?

Comment (itsarune) [reply src/software/sensor_fusion/sensor_fusion.cpp]: oh this was in the old code I see. you can delete this comment, I don't think it's relevant anymore

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 11]
```diff
@@ -875,3 +875,115 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
     result = *sensor_fusion.getWorld();
     EXPECT_EQ(initWorld(), result);
 }
+
+TEST_F(SensorFusionTest, breakbeam_pass_update_test)
+{
+    // The following code test this thing: if the breakbeam is triggered and the position
+    // of the robot and the ball given by the ssl vision system is less than a certain
+    // threshold, we expect shouldUseRobotBallPositionInsteadOfSSL to return True
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]: this comment is out-of-date

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 12]
```diff
@@ -875,3 +875,115 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
...
+    // times before the ball position is updated
+    sensor_fusion.processSensorProto(sensor_msg);
+    sensor_fusion.processSensorProto(sensor_msg);
+
+    Point updated_ball_pos = sensor_fusion.getWorld().value().ball().position();
+
+    // is it using the robot state position
+    EXPECT_TRUE(updated_ball_pos != robot_state.position());
+    // is it not using the ssl vision?
+    EXPECT_TRUE(updated_ball_pos == ssl_position);
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]: these assertions look contradictory to what the test is trying to do

**Review by itsarune — COMMENTED** [review]
getting close!

File: src/software/sensor_fusion/sensor_fusion_test.cpp (hunk 12 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: indeed.

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 13]
```diff
@@ -875,3 +875,139 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
     result = *sensor_fusion.getWorld();
     EXPECT_EQ(initWorld(), result);
 }
+
+TEST_F(SensorFusionTest, breakbeam_pass_update_test)
+{
+    // The following code test this thing: if the breakbeam is triggered and the position
+    // of the robot and the ball given by the ssl vision system is less than a certain
+    // threshold, we should expcet the ball position to be updated as the position of the
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]:
```suggestion
    // threshold, we should expect the ball position to be updated as the position of the
```

File: src/software/sensor_fusion/sensor_fusion_test.cpp [hunk 14]
```diff
@@ -875,3 +875,139 @@ TEST_F(SensorFusionTest, test_sensor_fusion_reset_behaviour_ignore_bad_packets)
...
+    // creating robot status
+    auto robot_msg = std::make_unique<TbotsProto::RobotStatus>();
+    robot_msg->set_robot_id(2);
+
+    auto power_status_msg = std::make_unique<TbotsProto::PowerStatus>();
+    power_status_msg->set_breakbeam_tripped(true);
+    *(robot_msg->mutable_power_status()) = *power_status_msg;
+
+    // create ssl wrapper packet
+    auto gemotry_data = initSSLDivBGeomData();
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion_test.cpp]: nit: 
```suggestion
    auto geometry_data = initSSLDivBGeomData();
```

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 15]
```diff
@@ -231,31 +265,26 @@ void SensorFusion::updateWorld(const SSLProto::SSL_DetectionFrame &ssl_detection
         ball_in_dribbler_timeout                = 0;
     }
 
-    if (friendly_robot_id_with_ball_in_dribbler.has_value())
+    if (shouldTrustRobotStatus(ssl_detection_frame, ball_detections))
     {
         std::optional<Robot> robot_with_ball_in_dribbler =
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp:266]: in the `else` case of this `if` statement:
reset `friendly_robot_id_with_ball_in_dribbler` to nullopt and set `ball_in_dribbler_timeout` back to 0

Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp:266]: done

File: src/software/sensor_fusion/sensor_fusion_test.cpp (hunk 14 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: done

File: src/software/sensor_fusion/sensor_fusion_test.cpp (hunk 13 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion_test.cpp]: done.

**Review by itsarune — DISMISSED** [review]
LGTM :100:

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 16]
```diff
@@ -180,6 +180,40 @@ void SensorFusion::updateWorld(
     }
 }
 
+bool SensorFusion::shouldTrustRobotStatus(
+    const SSLProto::SSL_DetectionFrame &ssl_detection_frame,
+    const std::vector<BallDetection> &ball_detection)
```
Comment (nimazareian) [inline src/software/sensor_fusion/sensor_fusion.cpp]: nit: both arguments seem to be unused. We should remove them if we actually dont need them.

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 17]
```diff
@@ -180,6 +180,40 @@ void SensorFusion::updateWorld(
...
+    if (distance > DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION)
+    {
+        return false;
+    }
+
+    // In other words, this is only true if we have the position of the breakbeam
+    // robot, and the distance between what the ssl says and where the robots are actually
+    // at is less that a threshold distance set by
+    // DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION
+    return true;
```
Comment (nimazareian) [inline src/software/sensor_fusion/sensor_fusion.cpp]: nit: Here's a suggestion for improving readability
```suggestion
    double distance =
        (robot_with_ball_in_dribbler.value().position() - ball.value().position())
            .length();
            
    // In other words, we trust the breakbeam reading from robot status if vision also agrees
    // that the ball is roughly near the robot. If vision has the ball far from the breakbeam detection, 
    // then we will ignore the breakbeam detection and trust vision instead.
    return distance <= DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION;
```

Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp]: done.

File: src/software/sensor_fusion/sensor_fusion.cpp (hunk 16 above)
Comment (Mr-Anyone) [reply src/software/sensor_fusion/sensor_fusion.cpp]: agreed.

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 18]
```diff
@@ -180,6 +180,34 @@ void SensorFusion::updateWorld(
...
+        return false;
+    }
+
+    double distance =
+        (robot_with_ball_in_dribbler.value().position() - ball.value().position())
+            .length();
+
+    // In other words, this is only true if we have the position of the breakbeam
+    // robot, and the distance between what the ssl says and where the robots are actually
+    // at is less that a threshold distance set by
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp:206]:
```suggestion
    // at is less than a threshold distance set by
```

File: src/software/sensor_fusion/sensor_fusion.cpp [hunk 19]
```diff
@@ -180,6 +180,34 @@ void SensorFusion::updateWorld(
...
+    // DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION
```
Comment (itsarune) [inline src/software/sensor_fusion/sensor_fusion.cpp]:
```suggestion
    // In other words, this is only true if we have the position of the breakbeam
    // robot, and the distance between what SSL says and where the robots are actually
    // at is less than a threshold distance set by
    // DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION
```

**Review by itsarune — COMMENTED** [review]
looks good pending nit and it looks like the CI fail is unrelated to you. You can restart it and it should pass

File: src/software/sensor_fusion/sensor_fusion.h [hunk 20]
```diff
@@ -55,6 +55,12 @@ class SensorFusion
     // started, determined experimentally with the simulator
     static constexpr double VISION_PACKET_RESET_TIME_THRESHOLD = 0.5;
 
+    // This is used for detecting if the breakbeam is at fault. The idea is that distance
+    // between the robot that has the ball is greater than the distance below, then we
+    // know that the breakbeam has a problem see for more:
+    // https://github.com/UBC-Thunderbots/Software/issues/3197
+    static constexpr double DISTANCE_THRESHOLD_FOR_BREAKBEAM_FAULT_DETECTION = 0.5;
```
Comment (williamckha) [inline src/software/sensor_fusion/sensor_fusion.h:62]: Should this be a dynamic param?

**Review by williamckha — APPROVED** [review]
LGTM

File: src/software/sensor_fusion/sensor_fusion.h (hunk 20 above)
Comment (nimazareian) [reply src/software/sensor_fusion/sensor_fusion.h:62]: Yeah it could be. Though it's probably fine without it as well. @Mr-Anyone if you do end up making the change, the min_value of the constant should probably not be less than 0.09 (robot radius) given that `distance` in `shouldTrustRobotStatus` is calculated from the _center_ of the robot to the ball (instead of dribbler position to the ball).

**Review by nimazareian — APPROVED** [review]
